services:
  service:
    container_name: bank_system_java
    build: .
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./data:/info

  database:
    container_name: bank_database
    image: 'postgres:15-alpine'
    env_file:
      - .env
    ports:
      - '5433:5432'


  # Prometheus & Grafana
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin